image: alpine/latest
packages:
  - go
sources:
  - https://git.sr.ht/~alexisgeoffrey/aoe4api
tasks:
  - build: |
      cd aoe4api
      go build -v ./...
  - lint: |
      wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
      cd aoe4api
      ~/bin/golangci-lint -v run
